---
- name: Include OS-specific vars
  include_vars: "{{ansible_os_family}}.yml"

- name: Include OS-specific tasks
  include_tasks: "install-{{ansible_os_family}}.yml"

- name: Include cadir-related tasks
  include_tasks: prepare-ca.yml

- name: Include setting server certs, configuration templates and useful files task
  include_tasks: confs-files.yml

- name: Enable openvpn service
  service:
    name: "{{openvpn_service_name}}"
    state: started
    enabled: yes
